CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	slug VARCHAR(120) NOT NULL UNIQUE,
	description VARCHAR(255) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	category_id INT UNSIGNED NULL,
	name VARCHAR(150) NOT NULL,
	slug VARCHAR(180) NOT NULL UNIQUE,
	manufacturer VARCHAR(120) NOT NULL,
	image VARCHAR(2048) NULL,
	short_description VARCHAR(255) NULL,
	description TEXT NULL,
	price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
	quantity INT UNSIGNED NOT NULL DEFAULT 0,
	is_available TINYINT(1) NOT NULL DEFAULT 1,
	sku VARCHAR(80) NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT fk_products_category
		FOREIGN KEY (category_id) REFERENCES categories(id)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);
